-- Парсер цін: магазини, категорії, матеріали з правилами, джерела. Згенеровано tools/price-parser/seed-sql.mjs

-- одиниці виміру
insert into public.material_units (name, sort_order)
select v.name, (select coalesce(max(sort_order), 0) from public.material_units) + v.n
from (values ('пара', 1), ('100 шт', 2), ('1000 шт', 3)) as v(name, n)
where not exists (select 1 from public.material_units u where u.name = v.name);

-- категорії матеріалів
insert into public.material_categories (name, icon, sort_order)
select v.name, v.icon, (select coalesce(max(sort_order), 0) from public.material_categories where parent_id is null) + v.n
from (values ('Дерево', '🪵', 1), ('Утеплювач', '🧱', 2), ('Плівки, мембрани, стрічки', '🧻', 3), ('Вікна і двері', '🪟', 4), ('Оздоблення', '🎨', 5), ('Покрівля', '🏠', 6), ('Витратні матеріали', '🧰', 7), ('Сітки та захист', '🕸️', 8)) as v(name, icon, n)
where not exists (select 1 from public.material_categories c where c.name = v.name);

-- магазини
insert into public.suppliers (name, region, website, parser_key, parser_enabled, parse_status, notes)
select v.name, 'Київ', v.website, v.key, v.enabled, v.status, 'Інтернет-магазин будматеріалів. Ціни оновлює парсер раз на день.'
from (values
  ('Епіцентр', 'https://epicentrk.ua/', 'epicentr', true, null),
  ('ОЛДІ', 'https://oldimarket.com.ua/', 'oldi', true, null),
  ('Budia', 'https://budia.ua/', 'budia', true, null),
  ('КУБ', 'https://kub.in.ua/', 'kub', true, null),
  ('Budmaterial', 'https://budmaterial.kyiv.ua/', 'budmaterial', true, null),
  ('М2', 'https://m2.org.ua/', 'm2', true, null),
  ('Woodmax', 'https://woodmax.ua/', 'woodmax', true, null),
  ('Alba Wood', 'https://www.alba-wood.com.ua/', 'albawood', true, null),
  ('Leroy Merlin', 'https://www.leroymerlin.ua/', 'leroymerlin', false, 'Сайт захищено від автоматичного збору даних (DataDome): справжньому браузеру показує капчу після кількох сторінок. Ціни — вручну або з прайсу від магазину.'),
  ('Angio', 'https://angio.com.ua/', 'angio', false, 'Сайт не пускає програми (перевірка Cloudflare «чи ви людина»). Ціни — вручну або з прайсу від магазину.')
) as v(name, website, key, enabled, status)
where not exists (select 1 from public.suppliers s where s.parser_key = v.key);
insert into public.supplier_contacts (supplier_id, type, value, label, sort_order)
select s.id, 'website', s.website, 'Сайт', 0 from public.suppliers s
where s.parser_key is not null and s.website is not null
  and not exists (select 1 from public.supplier_contacts c where c.supplier_id = s.id);

-- матеріали з правилами відстеження
with v(name, category, unit, spec, rule) as (values
  ('Брус 50×50 свіжопиляний', 'Дерево', 'м³', 'Сосна/ялина, переріз 50×50 мм, довжина будь-яка. Ціна за м³; у пропозиціях — ще за м.п. і за штуку.', '{"groups":["lumber"],"norm":"lumber","a":50,"b":50,"type":"fresh","all":["дошк|доск|брус|рейк|балк|лаг[аи]|стійк"],"none":"необрізн|необрезн|зрощ|сращ|клеєн|клеен|терас|палубн|лавочн|вагонк|фальш|імітац|имитац|блок.?хаус|планкен|дуб|ясен|вільх|ольх|липа|бук|модрин|лиственн|термо|шпунт|підлог|полов|наличник|плінтус|плинтус|поруч|балясин|щит|штахет|кіл[оь]к|колышек|стовп|столб|двп|дсп|осб|osb|фанер|піддон|поддон|дрова"}'::jsonb),
  ('Брус 50×50 сухий', 'Дерево', 'м³', 'Сосна/ялина, переріз 50×50 мм, довжина будь-яка. Ціна за м³; у пропозиціях — ще за м.п. і за штуку.', '{"groups":["lumber"],"norm":"lumber","a":50,"b":50,"type":"dry","all":["дошк|доск|брус|рейк|балк|лаг[аи]|стійк"],"none":"необрізн|необрезн|зрощ|сращ|клеєн|клеен|терас|палубн|лавочн|вагонк|фальш|імітац|имитац|блок.?хаус|планкен|дуб|ясен|вільх|ольх|липа|бук|модрин|лиственн|термо|шпунт|підлог|полов|наличник|плінтус|плинтус|поруч|балясин|щит|штахет|кіл[оь]к|колышек|стовп|столб|двп|дсп|осб|osb|фанер|піддон|поддон|дрова"}'::jsonb),
  ('Брус 50×50 сухий калібрований (струганий)', 'Дерево', 'м³', 'Сосна/ялина, переріз 50×50 мм, довжина будь-яка. Ціна за м³; у пропозиціях — ще за м.п. і за штуку.', '{"groups":["lumber"],"norm":"lumber","a":50,"b":50,"type":"planed","all":["дошк|доск|брус|рейк|балк|лаг[аи]|стійк"],"none":"необрізн|необрезн|зрощ|сращ|клеєн|клеен|терас|палубн|лавочн|вагонк|фальш|імітац|имитац|блок.?хаус|планкен|дуб|ясен|вільх|ольх|липа|бук|модрин|лиственн|термо|шпунт|підлог|полов|наличник|плінтус|плинтус|поруч|балясин|щит|штахет|кіл[оь]к|колышек|стовп|столб|двп|дсп|осб|osb|фанер|піддон|поддон|дрова"}'::jsonb),
  ('Дошка 50×100 свіжопиляна', 'Дерево', 'м³', 'Сосна/ялина, переріз 50×100 мм, довжина будь-яка. Ціна за м³; у пропозиціях — ще за м.п. і за штуку.', '{"groups":["lumber"],"norm":"lumber","a":50,"b":100,"type":"fresh","all":["дошк|доск|брус|рейк|балк|лаг[аи]|стійк"],"none":"необрізн|необрезн|зрощ|сращ|клеєн|клеен|терас|палубн|лавочн|вагонк|фальш|імітац|имитац|блок.?хаус|планкен|дуб|ясен|вільх|ольх|липа|бук|модрин|лиственн|термо|шпунт|підлог|полов|наличник|плінтус|плинтус|поруч|балясин|щит|штахет|кіл[оь]к|колышек|стовп|столб|двп|дсп|осб|osb|фанер|піддон|поддон|дрова"}'::jsonb),
  ('Дошка 50×100 суха', 'Дерево', 'м³', 'Сосна/ялина, переріз 50×100 мм, довжина будь-яка. Ціна за м³; у пропозиціях — ще за м.п. і за штуку.', '{"groups":["lumber"],"norm":"lumber","a":50,"b":100,"type":"dry","all":["дошк|доск|брус|рейк|балк|лаг[аи]|стійк"],"none":"необрізн|необрезн|зрощ|сращ|клеєн|клеен|терас|палубн|лавочн|вагонк|фальш|імітац|имитац|блок.?хаус|планкен|дуб|ясен|вільх|ольх|липа|бук|модрин|лиственн|термо|шпунт|підлог|полов|наличник|плінтус|плинтус|поруч|балясин|щит|штахет|кіл[оь]к|колышек|стовп|столб|двп|дсп|осб|osb|фанер|піддон|поддон|дрова"}'::jsonb),
  ('Дошка 50×100 суха калібрована (стругана)', 'Дерево', 'м³', 'Сосна/ялина, переріз 50×100 мм, довжина будь-яка. Ціна за м³; у пропозиціях — ще за м.п. і за штуку.', '{"groups":["lumber"],"norm":"lumber","a":50,"b":100,"type":"planed","all":["дошк|доск|брус|рейк|балк|лаг[аи]|стійк"],"none":"необрізн|необрезн|зрощ|сращ|клеєн|клеен|терас|палубн|лавочн|вагонк|фальш|імітац|имитац|блок.?хаус|планкен|дуб|ясен|вільх|ольх|липа|бук|модрин|лиственн|термо|шпунт|підлог|полов|наличник|плінтус|плинтус|поруч|балясин|щит|штахет|кіл[оь]к|колышек|стовп|столб|двп|дсп|осб|osb|фанер|піддон|поддон|дрова"}'::jsonb),
  ('Дошка 50×150 свіжопиляна', 'Дерево', 'м³', 'Сосна/ялина, переріз 50×150 мм, довжина будь-яка. Ціна за м³; у пропозиціях — ще за м.п. і за штуку.', '{"groups":["lumber"],"norm":"lumber","a":50,"b":150,"type":"fresh","all":["дошк|доск|брус|рейк|балк|лаг[аи]|стійк"],"none":"необрізн|необрезн|зрощ|сращ|клеєн|клеен|терас|палубн|лавочн|вагонк|фальш|імітац|имитац|блок.?хаус|планкен|дуб|ясен|вільх|ольх|липа|бук|модрин|лиственн|термо|шпунт|підлог|полов|наличник|плінтус|плинтус|поруч|балясин|щит|штахет|кіл[оь]к|колышек|стовп|столб|двп|дсп|осб|osb|фанер|піддон|поддон|дрова"}'::jsonb),
  ('Дошка 50×150 суха', 'Дерево', 'м³', 'Сосна/ялина, переріз 50×150 мм, довжина будь-яка. Ціна за м³; у пропозиціях — ще за м.п. і за штуку.', '{"groups":["lumber"],"norm":"lumber","a":50,"b":150,"type":"dry","all":["дошк|доск|брус|рейк|балк|лаг[аи]|стійк"],"none":"необрізн|необрезн|зрощ|сращ|клеєн|клеен|терас|палубн|лавочн|вагонк|фальш|імітац|имитац|блок.?хаус|планкен|дуб|ясен|вільх|ольх|липа|бук|модрин|лиственн|термо|шпунт|підлог|полов|наличник|плінтус|плинтус|поруч|балясин|щит|штахет|кіл[оь]к|колышек|стовп|столб|двп|дсп|осб|osb|фанер|піддон|поддон|дрова"}'::jsonb),
  ('Дошка 50×150 суха калібрована (стругана)', 'Дерево', 'м³', 'Сосна/ялина, переріз 50×150 мм, довжина будь-яка. Ціна за м³; у пропозиціях — ще за м.п. і за штуку.', '{"groups":["lumber"],"norm":"lumber","a":50,"b":150,"type":"planed","all":["дошк|доск|брус|рейк|балк|лаг[аи]|стійк"],"none":"необрізн|необрезн|зрощ|сращ|клеєн|клеен|терас|палубн|лавочн|вагонк|фальш|імітац|имитац|блок.?хаус|планкен|дуб|ясен|вільх|ольх|липа|бук|модрин|лиственн|термо|шпунт|підлог|полов|наличник|плінтус|плинтус|поруч|балясин|щит|штахет|кіл[оь]к|колышек|стовп|столб|двп|дсп|осб|osb|фанер|піддон|поддон|дрова"}'::jsonb),
  ('Дошка 50×200 свіжопиляна', 'Дерево', 'м³', 'Сосна/ялина, переріз 50×200 мм, довжина будь-яка. Ціна за м³; у пропозиціях — ще за м.п. і за штуку.', '{"groups":["lumber"],"norm":"lumber","a":50,"b":200,"type":"fresh","all":["дошк|доск|брус|рейк|балк|лаг[аи]|стійк"],"none":"необрізн|необрезн|зрощ|сращ|клеєн|клеен|терас|палубн|лавочн|вагонк|фальш|імітац|имитац|блок.?хаус|планкен|дуб|ясен|вільх|ольх|липа|бук|модрин|лиственн|термо|шпунт|підлог|полов|наличник|плінтус|плинтус|поруч|балясин|щит|штахет|кіл[оь]к|колышек|стовп|столб|двп|дсп|осб|osb|фанер|піддон|поддон|дрова"}'::jsonb),
  ('Дошка 50×200 суха', 'Дерево', 'м³', 'Сосна/ялина, переріз 50×200 мм, довжина будь-яка. Ціна за м³; у пропозиціях — ще за м.п. і за штуку.', '{"groups":["lumber"],"norm":"lumber","a":50,"b":200,"type":"dry","all":["дошк|доск|брус|рейк|балк|лаг[аи]|стійк"],"none":"необрізн|необрезн|зрощ|сращ|клеєн|клеен|терас|палубн|лавочн|вагонк|фальш|імітац|имитац|блок.?хаус|планкен|дуб|ясен|вільх|ольх|липа|бук|модрин|лиственн|термо|шпунт|підлог|полов|наличник|плінтус|плинтус|поруч|балясин|щит|штахет|кіл[оь]к|колышек|стовп|столб|двп|дсп|осб|osb|фанер|піддон|поддон|дрова"}'::jsonb),
  ('Дошка 50×200 суха калібрована (стругана)', 'Дерево', 'м³', 'Сосна/ялина, переріз 50×200 мм, довжина будь-яка. Ціна за м³; у пропозиціях — ще за м.п. і за штуку.', '{"groups":["lumber"],"norm":"lumber","a":50,"b":200,"type":"planed","all":["дошк|доск|брус|рейк|балк|лаг[аи]|стійк"],"none":"необрізн|необрезн|зрощ|сращ|клеєн|клеен|терас|палубн|лавочн|вагонк|фальш|імітац|имитац|блок.?хаус|планкен|дуб|ясен|вільх|ольх|липа|бук|модрин|лиственн|термо|шпунт|підлог|полов|наличник|плінтус|плинтус|поруч|балясин|щит|штахет|кіл[оь]к|колышек|стовп|столб|двп|дсп|осб|osb|фанер|піддон|поддон|дрова"}'::jsonb),
  ('Рейка 30×30 свіжопиляна', 'Дерево', 'м³', 'Сосна/ялина, переріз 30×30 мм, довжина будь-яка. Ціна за м³; у пропозиціях — ще за м.п. і за штуку.', '{"groups":["lumber"],"norm":"lumber","a":30,"b":30,"type":"fresh","all":["дошк|доск|брус|рейк|балк|лаг[аи]|стійк"],"none":"необрізн|необрезн|зрощ|сращ|клеєн|клеен|терас|палубн|лавочн|вагонк|фальш|імітац|имитац|блок.?хаус|планкен|дуб|ясен|вільх|ольх|липа|бук|модрин|лиственн|термо|шпунт|підлог|полов|наличник|плінтус|плинтус|поруч|балясин|щит|штахет|кіл[оь]к|колышек|стовп|столб|двп|дсп|осб|osb|фанер|піддон|поддон|дрова"}'::jsonb),
  ('Рейка 30×30 суха', 'Дерево', 'м³', 'Сосна/ялина, переріз 30×30 мм, довжина будь-яка. Ціна за м³; у пропозиціях — ще за м.п. і за штуку.', '{"groups":["lumber"],"norm":"lumber","a":30,"b":30,"type":"dry","all":["дошк|доск|брус|рейк|балк|лаг[аи]|стійк"],"none":"необрізн|необрезн|зрощ|сращ|клеєн|клеен|терас|палубн|лавочн|вагонк|фальш|імітац|имитац|блок.?хаус|планкен|дуб|ясен|вільх|ольх|липа|бук|модрин|лиственн|термо|шпунт|підлог|полов|наличник|плінтус|плинтус|поруч|балясин|щит|штахет|кіл[оь]к|колышек|стовп|столб|двп|дсп|осб|osb|фанер|піддон|поддон|дрова"}'::jsonb),
  ('Рейка 30×30 суха калібрована (стругана)', 'Дерево', 'м³', 'Сосна/ялина, переріз 30×30 мм, довжина будь-яка. Ціна за м³; у пропозиціях — ще за м.п. і за штуку.', '{"groups":["lumber"],"norm":"lumber","a":30,"b":30,"type":"planed","all":["дошк|доск|брус|рейк|балк|лаг[аи]|стійк"],"none":"необрізн|необрезн|зрощ|сращ|клеєн|клеен|терас|палубн|лавочн|вагонк|фальш|імітац|имитац|блок.?хаус|планкен|дуб|ясен|вільх|ольх|липа|бук|модрин|лиственн|термо|шпунт|підлог|полов|наличник|плінтус|плинтус|поруч|балясин|щит|штахет|кіл[оь]к|колышек|стовп|столб|двп|дсп|осб|osb|фанер|піддон|поддон|дрова"}'::jsonb),
  ('Дошка 20×100 свіжопиляна', 'Дерево', 'м³', 'Сосна/ялина, переріз 20×100 мм, довжина будь-яка. Ціна за м³; у пропозиціях — ще за м.п. і за штуку.', '{"groups":["lumber"],"norm":"lumber","a":20,"b":100,"type":"fresh","all":["дошк|доск|брус|рейк|балк|лаг[аи]|стійк"],"none":"необрізн|необрезн|зрощ|сращ|клеєн|клеен|терас|палубн|лавочн|вагонк|фальш|імітац|имитац|блок.?хаус|планкен|дуб|ясен|вільх|ольх|липа|бук|модрин|лиственн|термо|шпунт|підлог|полов|наличник|плінтус|плинтус|поруч|балясин|щит|штахет|кіл[оь]к|колышек|стовп|столб|двп|дсп|осб|osb|фанер|піддон|поддон|дрова"}'::jsonb),
  ('Дошка 20×100 суха', 'Дерево', 'м³', 'Сосна/ялина, переріз 20×100 мм, довжина будь-яка. Ціна за м³; у пропозиціях — ще за м.п. і за штуку.', '{"groups":["lumber"],"norm":"lumber","a":20,"b":100,"type":"dry","all":["дошк|доск|брус|рейк|балк|лаг[аи]|стійк"],"none":"необрізн|необрезн|зрощ|сращ|клеєн|клеен|терас|палубн|лавочн|вагонк|фальш|імітац|имитац|блок.?хаус|планкен|дуб|ясен|вільх|ольх|липа|бук|модрин|лиственн|термо|шпунт|підлог|полов|наличник|плінтус|плинтус|поруч|балясин|щит|штахет|кіл[оь]к|колышек|стовп|столб|двп|дсп|осб|osb|фанер|піддон|поддон|дрова"}'::jsonb),
  ('Дошка 20×100 суха калібрована (стругана)', 'Дерево', 'м³', 'Сосна/ялина, переріз 20×100 мм, довжина будь-яка. Ціна за м³; у пропозиціях — ще за м.п. і за штуку.', '{"groups":["lumber"],"norm":"lumber","a":20,"b":100,"type":"planed","all":["дошк|доск|брус|рейк|балк|лаг[аи]|стійк"],"none":"необрізн|необрезн|зрощ|сращ|клеєн|клеен|терас|палубн|лавочн|вагонк|фальш|імітац|имитац|блок.?хаус|планкен|дуб|ясен|вільх|ольх|липа|бук|модрин|лиственн|термо|шпунт|підлог|полов|наличник|плінтус|плинтус|поруч|балясин|щит|штахет|кіл[оь]к|колышек|стовп|столб|двп|дсп|осб|osb|фанер|піддон|поддон|дрова"}'::jsonb),
  ('Дошка 25×100 свіжопиляна', 'Дерево', 'м³', 'Сосна/ялина, переріз 25×100 мм, довжина будь-яка. Ціна за м³; у пропозиціях — ще за м.п. і за штуку.', '{"groups":["lumber"],"norm":"lumber","a":25,"b":100,"type":"fresh","all":["дошк|доск|брус|рейк|балк|лаг[аи]|стійк"],"none":"необрізн|необрезн|зрощ|сращ|клеєн|клеен|терас|палубн|лавочн|вагонк|фальш|імітац|имитац|блок.?хаус|планкен|дуб|ясен|вільх|ольх|липа|бук|модрин|лиственн|термо|шпунт|підлог|полов|наличник|плінтус|плинтус|поруч|балясин|щит|штахет|кіл[оь]к|колышек|стовп|столб|двп|дсп|осб|osb|фанер|піддон|поддон|дрова"}'::jsonb),
  ('Дошка 25×100 суха', 'Дерево', 'м³', 'Сосна/ялина, переріз 25×100 мм, довжина будь-яка. Ціна за м³; у пропозиціях — ще за м.п. і за штуку.', '{"groups":["lumber"],"norm":"lumber","a":25,"b":100,"type":"dry","all":["дошк|доск|брус|рейк|балк|лаг[аи]|стійк"],"none":"необрізн|необрезн|зрощ|сращ|клеєн|клеен|терас|палубн|лавочн|вагонк|фальш|імітац|имитац|блок.?хаус|планкен|дуб|ясен|вільх|ольх|липа|бук|модрин|лиственн|термо|шпунт|підлог|полов|наличник|плінтус|плинтус|поруч|балясин|щит|штахет|кіл[оь]к|колышек|стовп|столб|двп|дсп|осб|osb|фанер|піддон|поддон|дрова"}'::jsonb),
  ('Дошка 25×100 суха калібрована (стругана)', 'Дерево', 'м³', 'Сосна/ялина, переріз 25×100 мм, довжина будь-яка. Ціна за м³; у пропозиціях — ще за м.п. і за штуку.', '{"groups":["lumber"],"norm":"lumber","a":25,"b":100,"type":"planed","all":["дошк|доск|брус|рейк|балк|лаг[аи]|стійк"],"none":"необрізн|необрезн|зрощ|сращ|клеєн|клеен|терас|палубн|лавочн|вагонк|фальш|імітац|имитац|блок.?хаус|планкен|дуб|ясен|вільх|ольх|липа|бук|модрин|лиственн|термо|шпунт|підлог|полов|наличник|плінтус|плинтус|поруч|балясин|щит|штахет|кіл[оь]к|колышек|стовп|столб|двп|дсп|осб|osb|фанер|піддон|поддон|дрова"}'::jsonb),
  ('Базальтова вата 50 мм (плита для каркаса)', 'Утеплювач', 'м³', 'Плита 50 мм, легка (до 70 кг/м³), будь-який виробник і розмір плити. Ціна за м³; у пропозиціях — за упаковку й м².', '{"groups":["wool"],"norm":"pack_m3","thickness":50,"density":[20,70],"all":["вата|утепл|плит|теплоізол|теплоизол","базальт|камʼян|кам''ян|каменн|rockwool|роквул|rockmin|izovat|ізоват|изоват|paroc|термолайф|termolife|белтеп|beltep|sweetondale|технонік|техноник|technonicol|техноблок|технолайт|basfiber|izolux|роклайт|rocklight|basalt"],"none":"скловат|стекловат|скловолок|стекловолок|knauf|кнауф|isover|ізовер|изовер|ursa|урса|рулон|ламел|циліндр|цилиндр|фольг|шкаралуп|скорлуп|пінопласт|пенопласт|xps|eps|полістирол|полистирол|клей|дюбел|сендвіч|сэндвич|димох|дымоход","min":800,"max":12000}'::jsonb),
  ('Базальтова вата 100 мм (плита для каркаса)', 'Утеплювач', 'м³', 'Плита 100 мм, легка (до 70 кг/м³), будь-який виробник і розмір плити. Ціна за м³; у пропозиціях — за упаковку й м².', '{"groups":["wool"],"norm":"pack_m3","thickness":100,"density":[20,70],"all":["вата|утепл|плит|теплоізол|теплоизол","базальт|камʼян|кам''ян|каменн|rockwool|роквул|rockmin|izovat|ізоват|изоват|paroc|термолайф|termolife|белтеп|beltep|sweetondale|технонік|техноник|technonicol|техноблок|технолайт|basfiber|izolux|роклайт|rocklight|basalt"],"none":"скловат|стекловат|скловолок|стекловолок|knauf|кнауф|isover|ізовер|изовер|ursa|урса|рулон|ламел|циліндр|цилиндр|фольг|шкаралуп|скорлуп|пінопласт|пенопласт|xps|eps|полістирол|полистирол|клей|дюбел|сендвіч|сэндвич|димох|дымоход","min":800,"max":12000}'::jsonb),
  ('Мембрана супердифузійна (фасад, покрівля)', 'Плівки, мембрани, стрічки', 'м²', 'Вітро-вологозахисна паропроникна мембрана 80–250 г/м². Ціна за м²; у пропозиціях — за рулон і площа рулону.', '{"groups":["membrane"],"norm":"roll_m2","density":[80,250],"all":["мембран|плівк|пленк","супердиф|супер.?диф|дифузійн|диффузион"],"none":"скотч|стрічк|лента|клей|звукоізол|фундамент","min":8,"max":250}'::jsonb),
  ('Паробарʼєр (плівка)', 'Плівки, мембрани, стрічки', 'м²', 'Пароізоляційна плівка без фольги й армування. Ціна за м².', '{"groups":["membrane"],"norm":"roll_m2","all":["пароб|пароізол|парои|паро.?бар"],"none":"фольг|алюмін|алюмин|металіз|метализ|армов|армир|супердиф|скотч|стрічк|лента|мастик|клей","min":3,"max":150}'::jsonb),
  ('Паробарʼєр армований', 'Плівки, мембрани, стрічки', 'м²', 'Пароізоляційна плівка, армована сіткою. Ціна за м².', '{"groups":["membrane"],"norm":"roll_m2","all":["пароб|пароізол|парои|паро.?бар","армов|армир"],"none":"фольг|алюмін|алюмин|металіз|метализ|скотч|стрічк|лента","min":5,"max":200}'::jsonb),
  ('Паробарʼєр фольгований', 'Плівки, мембрани, стрічки', 'м²', 'Пароізоляція з алюмінієвим (відбивним) шаром. Ціна за м².', '{"groups":["membrane"],"norm":"roll_m2","all":["пароб|пароізол|парои|паро.?бар","фольг|алюмін|алюмин|металіз|метализ"],"none":"скотч|стрічк|лента","min":8,"max":300}'::jsonb),
  ('Скотч алюмінієвий (фольгований) для стиків', 'Плівки, мембрани, стрічки', 'м.п.', 'Алюмінієва клейка стрічка для проклейки стиків, рулони 40–50 м. Ціна за м.п.; у пропозиціях — за рулон.', '{"groups":["tape"],"norm":"roll_mp","all":["скотч|стрічк|лента","алюмін|алюмин|фольг"],"none":"бутил|бітум|битум|малярн|двосторон|двухсторон|герлен|димох|дымоход|флізелін|флизелин|вставк|серпянк","min":0.5,"max":80}'::jsonb),
  ('Стрічка для супердифузійних мембран (зʼєднувальна)', 'Плівки, мембрани, стрічки', 'м.п.', 'Клейка стрічка для зʼєднання й ремонту мембран і плівок. Ціна за м.п.; у пропозиціях — за рулон.', '{"groups":["tape"],"norm":"roll_mp","all":["скотч|стрічк|лента","мембран|пароізол|парои|пароб|плівок|пленок|eurovent|strotex|juta|ютафол|topband|uniband|unoband"],"none":"алюмін|алюмин|фольг|малярн|димох|дымоход|ущільн|уплотн|бітум|битум|примик|примык|звукоізол|демпфер|фундамент|ванн|душ","min":1,"max":250}'::jsonb),
  ('Вікно металопластикове Екіпаж Ultra 72 (профіль 72 мм), 2-камерний склопакет', 'Вікна і двері', 'м²', 'EKIPAZH Ultra 72: профіль 72 мм, 5 камер, склопакет 4-10-4-10-4і (3 скла). Ціна за м² без монтажу — з прайсу oknaekipazh.com.ua, оновлюємо вручну.', null::jsonb),
  ('Двері вхідні металопластикові Екіпаж Ultra 72 (профіль 72 мм), 2-камерний склопакет', 'Вікна і двері', 'м²', 'EKIPAZH Ultra 72 (COMFORT): профіль 72 мм, двері 900×2100 зі склопакетом 4-10-4-10-4i. Ціна за м² без монтажу — з прайсу oknaekipazh.com.ua, оновлюємо вручну.', null::jsonb),
  ('OSB-3 9 мм', 'Оздоблення', 'м²', 'Плита OSB-3 9 мм для чорнового оздоблення. Ціна за м²; у пропозиціях — за лист.', '{"groups":["osb"],"norm":"sheet_m2","thickness":9,"all":["osb|осб"],"none":"шпунт|qsb|ламін|ламин|гонт|черепиц|обрізк|обрезк","min":60,"max":1500}'::jsonb),
  ('OSB-3 10 мм', 'Оздоблення', 'м²', 'Плита OSB-3 10 мм для чорнового оздоблення. Ціна за м²; у пропозиціях — за лист.', '{"groups":["osb"],"norm":"sheet_m2","thickness":10,"all":["osb|осб"],"none":"шпунт|qsb|ламін|ламин|гонт|черепиц|обрізк|обрезк","min":60,"max":1500}'::jsonb),
  ('OSB-3 12 мм', 'Оздоблення', 'м²', 'Плита OSB-3 12 мм для чорнового оздоблення. Ціна за м²; у пропозиціях — за лист.', '{"groups":["osb"],"norm":"sheet_m2","thickness":12,"all":["osb|осб"],"none":"шпунт|qsb|ламін|ламин|гонт|черепиц|обрізк|обрезк","min":60,"max":1500}'::jsonb),
  ('OSB-3 15 мм', 'Оздоблення', 'м²', 'Плита OSB-3 15 мм для чорнового оздоблення. Ціна за м²; у пропозиціях — за лист.', '{"groups":["osb"],"norm":"sheet_m2","thickness":15,"all":["osb|осб"],"none":"шпунт|qsb|ламін|ламин|гонт|черепиц|обрізк|обрезк","min":60,"max":1500}'::jsonb),
  ('OSB-3 18 мм', 'Оздоблення', 'м²', 'Плита OSB-3 18 мм для чорнового оздоблення. Ціна за м²; у пропозиціях — за лист.', '{"groups":["osb"],"norm":"sheet_m2","thickness":18,"all":["osb|осб"],"none":"шпунт|qsb|ламін|ламин|гонт|черепиц|обрізк|обрезк","min":60,"max":1500}'::jsonb),
  ('OSB-3 22 мм', 'Оздоблення', 'м²', 'Плита OSB-3 22 мм для чорнового оздоблення. Ціна за м²; у пропозиціях — за лист.', '{"groups":["osb"],"norm":"sheet_m2","thickness":22,"all":["osb|осб"],"none":"шпунт|qsb|ламін|ламин|гонт|черепиц|обрізк|обрезк","min":60,"max":1500}'::jsonb),
  ('Фанера 9–10 мм', 'Оздоблення', 'м²', 'Фанера ФК/ФСФ шліфована. Ціна за м² — серединна серед знайдених (ґатунки різні — дивись пропозиції).', '{"groups":["plywood"],"norm":"sheet_m2","thickness":[9,10],"agg":"median","all":["фанер"],"none":"ламін|ламин|транспорт|перфор|гнучк|гибк|шпон|обрізк|обрезк|двп|мдф|осб|osb","min":100,"max":4000}'::jsonb),
  ('Фанера 12 мм', 'Оздоблення', 'м²', 'Фанера ФК/ФСФ шліфована. Ціна за м² — серединна серед знайдених (ґатунки різні — дивись пропозиції).', '{"groups":["plywood"],"norm":"sheet_m2","thickness":12,"agg":"median","all":["фанер"],"none":"ламін|ламин|транспорт|перфор|гнучк|гибк|шпон|обрізк|обрезк|двп|мдф|осб|osb","min":100,"max":4000}'::jsonb),
  ('Фанера 15 мм', 'Оздоблення', 'м²', 'Фанера ФК/ФСФ шліфована. Ціна за м² — серединна серед знайдених (ґатунки різні — дивись пропозиції).', '{"groups":["plywood"],"norm":"sheet_m2","thickness":15,"agg":"median","all":["фанер"],"none":"ламін|ламин|транспорт|перфор|гнучк|гибк|шпон|обрізк|обрезк|двп|мдф|осб|osb","min":100,"max":4000}'::jsonb),
  ('Фанера 18 мм', 'Оздоблення', 'м²', 'Фанера ФК/ФСФ шліфована. Ціна за м² — серединна серед знайдених (ґатунки різні — дивись пропозиції).', '{"groups":["plywood"],"norm":"sheet_m2","thickness":18,"agg":"median","all":["фанер"],"none":"ламін|ламин|транспорт|перфор|гнучк|гибк|шпон|обрізк|обрезк|двп|мдф|осб|osb","min":100,"max":4000}'::jsonb),
  ('Імітація бруса', 'Оздоблення', 'м²', 'Обшивальна дошка «імітація бруса» (сосна/ялина). Ціна за м²; у пропозиціях — за штуку й м.п.', '{"groups":["cladding"],"norm":"board_m2","all":["імітац|имитац|фальш.?брус"],"none":"куток|уголок|плінтус|плинтус|наличник|кліпс|кляймер","min":150,"max":3000}'::jsonb),
  ('Планкен скошений', 'Оздоблення', 'м²', 'Планкен зі скошеною кромкою — для фасаду й інтерʼєру. Ціна за м²; у пропозиціях — за штуку й м.п.', '{"groups":["cladding"],"norm":"board_m2","all":["планкен"],"none":"прям|кріплен|креплен|кліпс|кляймер|саморіз|саморез|термо|модрин|лиственн","min":200,"max":5000}'::jsonb),
  ('Гіпсокартон стіновий 12,5 мм', 'Оздоблення', 'м²', 'Стандартний ГКЛ 12,5 мм. Ціна за м²; у пропозиціях — за лист.', '{"groups":["drywall"],"norm":"sheet_m2","thickness":12.5,"all":["гіпсокартон|гипсокартон|гкл|гкп"],"none":"вологост|влагост|вогнест|огнест|профіл|профил|клей|саморіз|саморез|стрічк|лента|дюбел|арков|гнучк|гибк|шпакл|акуст","min":40,"max":600}'::jsonb),
  ('Гіпсокартон вологостійкий 12,5 мм', 'Оздоблення', 'м²', 'Вологостійкий ГКЛВ 12,5 мм. Ціна за м²; у пропозиціях — за лист.', '{"groups":["drywall"],"norm":"sheet_m2","thickness":12.5,"all":["гіпсокартон|гипсокартон|гкл|гкп","вологост|влагост"],"none":"вогнест|огнест|профіл|профил|клей|саморіз|саморез|стрічк|лента|дюбел|шпакл","min":40,"max":800}'::jsonb),
  ('ПВХ мембрана армована 1,5 мм', 'Покрівля', 'м²', 'Покрівельна ПВХ мембрана, армована поліестером, 1,5 мм. Ціна за м²; у пропозиціях — за рулон.', '{"groups":["roof_pvc"],"norm":"roll_m2","thickness":[1.45,1.55],"all":["пвх|pvc","мембран"],"none":"басейн|бассейн|ставк|пруд|неармов","min":100,"max":1200}'::jsonb),
  ('Геотекстиль 300–500 г/м² (підкладка під мембрану)', 'Покрівля', 'м²', 'Голкопробивний геотекстиль як розділювальний шар під ПВХ мембрану. Ціна за м².', '{"groups":["geotextile"],"norm":"roll_m2","density":[280,520],"all":["геотекстил"],"min":8,"max":250}'::jsonb),
  ('Скоби для степлера', 'Витратні матеріали', '1000 шт', 'Скоби для монтажу плівок і мембран (тип 53/140, 8–14 мм). Серединна ціна за 1000 шт.', '{"groups":["staples"],"norm":"piece","per":1000,"agg":"median","all":["скоб"],"none":"такелаж|будівельн|строительн|кабел|канцеляр|антистеплер|кріплен|креплен|труб|№ ?(10|24|26)\\b","min":15,"max":1500}'::jsonb),
  ('Цвяхи для пневмопістолета', 'Витратні матеріали', '1000 шт', 'Цвяхи в касетах/барабанах для пневматичних нейлерів. Серединна ціна за 1000 шт.', '{"groups":["nails"],"norm":"piece","per":1000,"agg":"median","all":["цвях|гвозд","пневм|барабан|реєчн|реечн|пістолет|пистолет|нейлер|обойм|касет|кассет"],"min":30,"max":5000}'::jsonb),
  ('Шурупи конструкційні', 'Витратні матеріали', '100 шт', 'Конструкційні шурупи по дереву (розміри різні — дивись пропозиції). Серединна ціна за 100 шт.', '{"groups":["screws"],"norm":"piece","per":100,"agg":"median","all":["конструкц","шуруп|саморіз|саморез|гвинт|винт"],"min":20,"max":20000}'::jsonb),
  ('Рукавиці робочі', 'Витратні матеріали', 'пара', 'Трикотажні робочі рукавиці з покриттям. Серединна ціна за пару.', '{"groups":["gloves"],"norm":"piece","agg":"median","all":["рукавиц|рукавич|перчат"],"none":"зварюв|сварщ|діелектр|диэлектр|одноразов|кухон|садов|зимов|утепл|спилк|краг|набір|набор|латексні 100|нітрилові 100|медич","min":8,"max":250}'::jsonb),
  ('Олівець будівельний', 'Витратні матеріали', 'шт', 'Столярний/будівельний олівець. Серединна ціна за штуку.', '{"groups":["pencil"],"norm":"piece","agg":"median","all":["олів[еє]?ц|карандаш","будів|строит|столяр|тесляр|плотн|муляр|каменщ"],"none":"точилк|стругалк","min":3,"max":300}'::jsonb),
  ('Пензель малярний', 'Витратні матеріали', 'шт', 'Плоский малярний пензель (розміри різні). Серединна ціна за штуку.', '{"groups":["brush"],"norm":"piece","agg":"median","all":["пензел|пензл|кисть|кисти|кисточ"],"none":"макловиц|набір|набор|художн|радіатор|радиатор|щітк|щетк","min":8,"max":600}'::jsonb),
  ('Макловиця', 'Витратні матеріали', 'шт', 'Макловиця для ґрунтування й просочення. Серединна ціна за штуку.', '{"groups":["brush"],"norm":"piece","agg":"median","all":["макловиц"],"none":"набір|набор","min":20,"max":900}'::jsonb),
  ('Сітка металева, вічко до 6×6 мм (захист від гризунів)', 'Сітки та захист', 'м²', 'Зварна/ткана оцинкована сітка з вічком не більше 6×6 мм — під будинок. Ціна за м²; у пропозиціях — за рулон.', '{"groups":["mesh"],"norm":"roll_m2","cell_max":6.5,"all":["сітк|сетк","зварн|сварн|оцинк|метал|ткан|нержав|просічн|просечн|цпвс|сталев|стальн"],"none":"пластик|склосіт|стеклосет|скловолок|стекловолок|полімер|полимер|композит|москіт|москит|абразив|фасадн|затін|затен|маскув|маскир|серпянк|малярн","min":15,"max":2500}'::jsonb)
), upd as (
  update public.materials m set parse_rule = v.rule, spec = v.spec
  from v where m.name = v.name
  returning m.name
)
insert into public.materials (name, category_id, unit, spec, parse_rule)
select v.name, (select c.id from public.material_categories c where c.name = v.category order by c.parent_id nulls first limit 1), v.unit, v.spec, v.rule
from v where v.name not in (select name from upd);

-- джерела: сторінки категорій
insert into public.price_sources (supplier_id, grp, url, max_pages)
select s.id, v.grp, v.url, v.max_pages
from (values
  ('epicentr', 'lumber', 'https://epicentrk.ua/ua/shop/brusy-doski-i-reyki/', 25),
  ('epicentr', 'wool', 'https://epicentrk.ua/ua/shop/bazaltovaya-i-mineralnaya-vata/', 25),
  ('epicentr', 'membrane', 'https://epicentrk.ua/ua/shop/krovelnye-plenki-i-membrany/', 25),
  ('epicentr', 'tape', 'https://epicentrk.ua/ua/shop/krovelnye-lenty/', 6),
  ('epicentr', 'tape', 'https://epicentrk.ua/ua/shop/lenty-stroitelno-montazhnye/', 6),
  ('epicentr', 'tape', 'https://epicentrk.ua/ua/shop/kleykie-lenty/', 6),
  ('epicentr', 'osb', 'https://epicentrk.ua/ua/shop/osb-plity/', 25),
  ('epicentr', 'plywood', 'https://epicentrk.ua/ua/shop/fanera/', 25),
  ('epicentr', 'drywall', 'https://epicentrk.ua/ua/shop/gipsokarton/', 25),
  ('epicentr', 'cladding', 'https://epicentrk.ua/ua/shop/vagonka/', 25),
  ('epicentr', 'cladding', 'https://epicentrk.ua/ua/shop/brusy-doski-i-reyki/fs/typ-tovaru-falsh-brus/', 25),
  ('epicentr', 'cladding', 'https://epicentrk.ua/ua/search/?q=%D0%BF%D0%BB%D0%B0%D0%BD%D0%BA%D0%B5%D0%BD', 2),
  ('epicentr', 'cladding', 'https://epicentrk.ua/ua/search/?q=%D1%96%D0%BC%D1%96%D1%82%D0%B0%D1%86%D1%96%D1%8F%20%D0%B1%D1%80%D1%83%D1%81%D0%B0', 2),
  ('epicentr', 'roof_pvc', 'https://epicentrk.ua/ua/search/?q=%D0%BF%D0%B2%D1%85%20%D0%BC%D0%B5%D0%BC%D0%B1%D1%80%D0%B0%D0%BD%D0%B0%20%D0%BF%D0%BE%D0%BA%D1%80%D1%96%D0%B2%D0%B5%D0%BB%D1%8C%D0%BD%D0%B0', 2),
  ('epicentr', 'geotextile', 'https://epicentrk.ua/ua/search/?q=%D0%B3%D0%B5%D0%BE%D1%82%D0%B5%D0%BA%D1%81%D1%82%D0%B8%D0%BB%D1%8C', 2),
  ('epicentr', 'staples', 'https://epicentrk.ua/ua/shop/skoby-dlya-steplera/', 3),
  ('epicentr', 'nails', 'https://epicentrk.ua/ua/shop/gvozdi/', 4),
  ('epicentr', 'screws', 'https://epicentrk.ua/ua/shop/shurupy/', 4),
  ('epicentr', 'gloves', 'https://epicentrk.ua/ua/shop/rukavitsy-i-perchatki-stroitelnye/', 3),
  ('epicentr', 'pencil', 'https://epicentrk.ua/ua/search/?q=%D0%BE%D0%BB%D1%96%D0%B2%D0%B5%D1%86%D1%8C%20%D1%81%D1%82%D0%BE%D0%BB%D1%8F%D1%80%D0%BD%D0%B8%D0%B9', 2),
  ('epicentr', 'brush', 'https://epicentrk.ua/ua/shop/kisti-malyarnye/', 3),
  ('epicentr', 'mesh', 'https://epicentrk.ua/ua/shop/setka-svarnaya/', 25),
  ('epicentr', 'mesh', 'https://epicentrk.ua/ua/search/?q=%D1%81%D1%96%D1%82%D0%BA%D0%B0%20%D0%BE%D1%86%D0%B8%D0%BD%D0%BA%D0%BE%D0%B2%D0%B0%D0%BD%D0%B0%206%D1%856', 2),
  ('epicentr', 'mesh', 'https://epicentrk.ua/ua/search/?q=%D1%81%D1%96%D1%82%D0%BA%D0%B0%20%D0%B2%D1%96%D0%B4%20%D0%B3%D1%80%D0%B8%D0%B7%D1%83%D0%BD%D1%96%D0%B2', 2),
  ('oldi', 'lumber', 'https://oldimarket.com.ua/category/doshky/', 15),
  ('oldi', 'lumber', 'https://oldimarket.com.ua/category/brusy/', 15),
  ('oldi', 'wool', 'https://oldimarket.com.ua/category/vata_izolyatsiyna/', 15),
  ('oldi', 'membrane', 'https://oldimarket.com.ua/category/pokrivelni_plivky/', 15),
  ('oldi', 'membrane', 'https://oldimarket.com.ua/category/plivky_budivelni/', 15),
  ('oldi', 'tape', 'https://oldimarket.com.ua/category/pokrivelni_strichky/', 6),
  ('oldi', 'tape', 'https://oldimarket.com.ua/category/strichky_kleyki_skotch/', 6),
  ('oldi', 'osb', 'https://oldimarket.com.ua/category/plyty_osb/', 15),
  ('oldi', 'plywood', 'https://oldimarket.com.ua/category/fanera/', 15),
  ('oldi', 'drywall', 'https://oldimarket.com.ua/category/hipsokarton/', 15),
  ('oldi', 'cladding', 'https://oldimarket.com.ua/category/vahonka/', 15),
  ('oldi', 'staples', 'https://oldimarket.com.ua/category/skoby/', 3),
  ('oldi', 'nails', 'https://oldimarket.com.ua/category/tsvyakhy/', 4),
  ('oldi', 'screws', 'https://oldimarket.com.ua/category/shurupy/', 4),
  ('oldi', 'screws', 'https://oldimarket.com.ua/category/samorizy/', 4),
  ('oldi', 'gloves', 'https://oldimarket.com.ua/category/rukavytsi/', 3),
  ('oldi', 'brush', 'https://oldimarket.com.ua/category/penzli_maklovytsi/', 3),
  ('oldi', 'pencil', 'https://oldimarket.com.ua/category/olivtsi_markery/', 2),
  ('oldi', 'mesh', 'https://oldimarket.com.ua/category/sitka_v_rulonakh/', 15),
  ('oldi', 'mesh', 'https://oldimarket.com.ua/category/sitka_dlya_ohorozhi/', 15),
  ('budia', 'lumber', 'https://budia.ua/armatura-brus-doska', 15),
  ('budia', 'lumber', 'https://budia.ua/svezhepil-strogannyi', 15),
  ('budia', 'wool', 'https://budia.ua/penoplast-stirodur-vata', 15),
  ('budia', 'membrane', 'https://budia.ua/setki', 15),
  ('budia', 'membrane', 'https://budia.ua/krovlia', 15),
  ('budia', 'osb', 'https://budia.ua/osb', 15),
  ('budia', 'plywood', 'https://budia.ua/osb', 15),
  ('budia', 'drywall', 'https://budia.ua/gipsokarton', 15),
  ('budia', 'mesh', 'https://budia.ua/setki', 15),
  ('kub', 'lumber', 'https://kub.in.ua/leso-pilomaterialy/brus/', 15),
  ('kub', 'lumber', 'https://kub.in.ua/leso-pilomaterialy/doska/', 15),
  ('kub', 'wool', 'https://kub.in.ua/uteplitel/mineralnaya-vata/', 15),
  ('kub', 'osb', 'https://kub.in.ua/leso-pilomaterialy/osb-i-qsb/', 15),
  ('kub', 'plywood', 'https://kub.in.ua/leso-pilomaterialy/fanera/', 15),
  ('kub', 'drywall', 'https://kub.in.ua/gipsokarton-i-profil/gipsokarton/', 15),
  ('kub', 'nails', 'https://kub.in.ua/krepezh/gvozdi/', 4),
  ('kub', 'screws', 'https://kub.in.ua/krepezh/samorezy/samorezy-po-derevu/', 4),
  ('budmaterial', 'lumber', 'https://budmaterial.kyiv.ua/pylomaterialy/', 15),
  ('budmaterial', 'wool', 'https://budmaterial.kyiv.ua/materialy-dlya-uteplennya/mineralna-vata/', 15),
  ('budmaterial', 'membrane', 'https://budmaterial.kyiv.ua/pokrivelni-materialy/membrany-baryery/', 15),
  ('budmaterial', 'osb', 'https://budmaterial.kyiv.ua/pylomaterialy/plyty-osb/', 15),
  ('budmaterial', 'drywall', 'https://budmaterial.kyiv.ua/gipsokartonni-systemy/', 15),
  ('m2', 'lumber', 'https://m2.org.ua/pylomaterialy/doshka/doshka-obrizna', 15),
  ('m2', 'lumber', 'https://m2.org.ua/pylomaterialy/brus', 15),
  ('m2', 'wool', 'https://m2.org.ua/utepljuvach/mineralna-vata', 15),
  ('m2', 'membrane', 'https://m2.org.ua/utepljuvach/gidrobarier', 15),
  ('m2', 'membrane', 'https://m2.org.ua/utepljuvach/parobarier', 15),
  ('m2', 'membrane', 'https://m2.org.ua/pokrivelni-materialy/paroizoljatsija-ta-gidroizoljatsija', 15),
  ('m2', 'tape', 'https://m2.org.ua/budivelnyi-inventar/vytratni-materialy/budivelnyi-skotch', 6),
  ('m2', 'tape', 'https://m2.org.ua/budivelnyi-inventar/vytratni-materialy/strichka', 6),
  ('m2', 'osb', 'https://m2.org.ua/pylomaterialy/osb', 15),
  ('m2', 'plywood', 'https://m2.org.ua/pylomaterialy/fanera', 15),
  ('m2', 'drywall', 'https://m2.org.ua/gipsokartonni-systemy/gipsokarton', 15),
  ('m2', 'geotextile', 'https://m2.org.ua/dvir-i-gorod/geotekstyl', 3),
  ('m2', 'staples', 'https://m2.org.ua/budivelnyi-inventar/ruchnyi-instrument/budivelnyi-stepler-ruchnyi/skoby-dlja-steplera', 3),
  ('m2', 'nails', 'https://m2.org.ua/kriplennja/tsvjakhy', 4),
  ('m2', 'screws', 'https://m2.org.ua/kriplennja/shurupy', 4),
  ('m2', 'screws', 'https://m2.org.ua/kriplennja/samonarizy/samorizy-po-derevu', 4),
  ('m2', 'gloves', 'https://m2.org.ua/budivelnyi-inventar/rukavychky-i-rukavytsi', 3),
  ('m2', 'brush', 'https://m2.org.ua/budivelnyi-inventar/maljarnyi-instrument', 3),
  ('m2', 'mesh', 'https://m2.org.ua/metalevi-sitky/sitka-zvarna', 15),
  ('m2', 'mesh', 'https://m2.org.ua/kutnyky-majaky-sitka/sitka-shtukaturna', 15),
  ('woodmax', 'lumber', 'https://woodmax.ua/cat/obreznaya-doska/', 15),
  ('woodmax', 'lumber', 'https://woodmax.ua/cat/strogonnaya-doska/', 15),
  ('albawood', 'lumber', 'https://www.alba-wood.com.ua/brus-obriznyj?limit=100', 15),
  ('albawood', 'lumber', 'https://www.alba-wood.com.ua/doshka-obrizna?limit=100', 15),
  ('albawood', 'lumber', 'https://www.alba-wood.com.ua/rejka-obrizna?limit=100', 15),
  ('albawood', 'lumber', 'https://www.alba-wood.com.ua/brus-suhyj?limit=100', 15),
  ('albawood', 'lumber', 'https://www.alba-wood.com.ua/doshka-suha-obrizna?limit=100', 15),
  ('albawood', 'lumber', 'https://www.alba-wood.com.ua/doshka-suha-strugana?limit=100', 15),
  ('albawood', 'lumber', 'https://www.alba-wood.com.ua/brus-suhyj-struganyj?limit=100', 15),
  ('leroymerlin', 'lumber', 'https://www.leroymerlin.ua/f/doshky', 1),
  ('leroymerlin', 'lumber', 'https://www.leroymerlin.ua/f/brus-ta-reiky', 1),
  ('leroymerlin', 'wool', 'https://www.leroymerlin.ua/f/bazaltova-vata', 1),
  ('leroymerlin', 'membrane', 'https://www.leroymerlin.ua/f/superdyfuziina-membrana', 1),
  ('leroymerlin', 'membrane', 'https://www.leroymerlin.ua/f/paroizoliatsiini-plivky', 1),
  ('leroymerlin', 'tape', 'https://www.leroymerlin.ua/f/aliuminiieva-strichka', 1),
  ('leroymerlin', 'tape', 'https://www.leroymerlin.ua/f/pokrivelni-strichky', 1),
  ('leroymerlin', 'osb', 'https://www.leroymerlin.ua/f/osb-plyty', 1),
  ('leroymerlin', 'plywood', 'https://www.leroymerlin.ua/f/fanera', 1),
  ('leroymerlin', 'drywall', 'https://www.leroymerlin.ua/f/gipsokarton', 1),
  ('leroymerlin', 'cladding', 'https://www.leroymerlin.ua/f/dereviana-vagonka', 1),
  ('leroymerlin', 'staples', 'https://www.leroymerlin.ua/f/skoby-ta-gvizdky-dlia-pnevmoinstrumentu', 1),
  ('leroymerlin', 'nails', 'https://www.leroymerlin.ua/f/tsviakhy', 1),
  ('leroymerlin', 'screws', 'https://www.leroymerlin.ua/f/shurupy', 1),
  ('leroymerlin', 'gloves', 'https://www.leroymerlin.ua/f/rukavychky', 1),
  ('leroymerlin', 'brush', 'https://www.leroymerlin.ua/f/penzli-maliarni', 1),
  ('leroymerlin', 'pencil', 'https://www.leroymerlin.ua/f/rozmitochni-instrumenty-olivtsi-markery-kreida', 1),
  ('leroymerlin', 'mesh', 'https://www.leroymerlin.ua/f/sitka-metaleva', 1),
  ('angio', 'lumber', 'https://angio.com.ua/ua/ishop/doska_obreznaya/', 1),
  ('angio', 'lumber', 'https://angio.com.ua/ua/ishop/brus/', 1),
  ('angio', 'wool', 'https://angio.com.ua/ua/ishop/bazaltovaya_vata/', 1),
  ('angio', 'membrane', 'https://angio.com.ua/ua/ishop/izoliacionnye_plenki/', 1),
  ('angio', 'tape', 'https://angio.com.ua/ua/ishop/lenty-germetiki/', 1),
  ('angio', 'osb', 'https://angio.com.ua/ua/ishop/osb/', 1),
  ('angio', 'plywood', 'https://angio.com.ua/ua/ishop/fanera/', 1),
  ('angio', 'drywall', 'https://angio.com.ua/ua/ishop/gipsokarton/', 1),
  ('angio', 'cladding', 'https://angio.com.ua/ua/ishop/vagonka/', 1),
  ('angio', 'geotextile', 'https://angio.com.ua/ua/ishop/geotekstil/', 1),
  ('angio', 'nails', 'https://angio.com.ua/ua/ishop/gvozdi/', 1),
  ('angio', 'screws', 'https://angio.com.ua/ua/ishop/shurupy/', 1),
  ('angio', 'gloves', 'https://angio.com.ua/ua/ishop/perchatki/', 1),
  ('angio', 'brush', 'https://angio.com.ua/ua/ishop/malyarnyy_instrument/kisti/', 1),
  ('angio', 'brush', 'https://angio.com.ua/ua/ishop/malyarnyy_instrument/maklovicy/', 1),
  ('angio', 'mesh', 'https://angio.com.ua/ua/ishop/metallicheskaya_setka/', 1)
) as v(site, grp, url, max_pages)
join public.suppliers s on s.parser_key = v.site
on conflict (supplier_id, grp, url) do nothing;
